### ISSUE TITLE
Two small issues

### ISSUE THREAD

**Issue by atlanteh** [pofigizm/redux-dynamic-middlewares#5]
Fantastic work you did here mate! thx!
We have few minor issues.
1. You specified in package.json this library is MIT. Can you please also include the license here?
2. You module is global, and our product should be used in an external app which might have it's own store and might use this product as well and a collision might happen. We need to have an option to instantiate this module and have it running separately.

**EDIT**
actually we have another one.
You pass to the middlewares an object with dispatch & getState, why do you not pass the entire store?
 this might break if there are middlewares that rely on other apis of store (like subscribe)

**Comment by pofigizm** [comment]
Thank you for your feedback.
1 and 3 are good points and pretty simple. So i going to solve it in few days.
2 point is a bit complicated (can lost simple API). Could you show some examples of good API for this idea?

p.s. And also you can create pull request. Don't be shy! ))

**Comment by navneet-g** [comment]
Thanks for creating redux-dynamic-middleware, this is really good utility.
This is pretty close to what I am looking for,  I just need support for 2 as well.
I created a PR for fixing 2 and then realized that you already have similar changes in another branch, so closing my PR.
By when do you plan to merge those changes to master?

I am working on [redux-dynamic-modules](https://github.com/Microsoft/redux-dynamic-modules) which is coupled with [redux-saga](https://redux-saga.js.org/docs/introduction/).
My motivation is to decouple them by using redux-dynamic-middleware.

**Comment by pofigizm** [comment]
@navneet-g @atlanteh
I released new version 1.0.0 which allow multi instanstences.
Thank you.
