### ISSUE TITLE
`addMiddleware` deprecated?

### ISSUE THREAD

**Issue by hamstu** [pofigizm/redux-dynamic-middlewares#9]
![image](https://user-images.githubusercontent.com/809093/105733387-5cf54900-5ee6-11eb-9d83-605e033490d2.png)

Seeing this in VS Code. Not sure where it's coming from. It still works fine.

**Comment by pofigizm** [comment]
No. I didn't change it.

**Comment by hamstu** [comment]
Cool. Figured it was some bug in VS Code. 👍🏻
